---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault-shim
  namespace: vault-shim
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-shim
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vault-shim
  namespace: vault-shim
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vault-shim
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
